// Generated by CoffeeScript 1.7.1
var CanvasH, ClockMaths, Minutes, Seconds, Vertex, initCanvas, update,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

CanvasH = (function() {
  CanvasH.prototype.context = null;

  CanvasH.prototype.element = null;

  CanvasH.prototype.events = {
    m: "minutePassed",
    h: "hourPassed"
  };

  function CanvasH() {
    this.on = __bind(this.on, this);
    this.element = document.getElementById("myCanvas");
    this.context = this.element.getContext("2d");
  }

  CanvasH.prototype.on = function(eventName, listener) {
    return this.element.addEventListener(eventName, listener);
  };

  CanvasH.prototype.trigger = function(eventName) {
    var event;
    if (document.createEvent) {
      event = document.createEvent("HTMLEvents");
      event.initEvent(eventName, true, true);
    } else {
      event = document.createEventObject();
      event.eventType = eventName;
    }
    event.eventName = eventName;
    if (document.createEvent) {
      return this.element.dispatchEvent(event);
    } else {
      return this.element.fireEvent("on" + event.eventType, event);
    }
  };

  return CanvasH;

})();

Vertex = (function() {
  Vertex.prototype.x = 0;

  Vertex.prototype.y = 0;

  function Vertex(x, y) {
    this.x = x != null ? x : 0;
    this.y = y != null ? y : 0;
  }

  return Vertex;

})();

ClockMaths = (function() {
  function ClockMaths() {}

  ClockMaths.prototype.CalculateSecondVertex = function(start, hypotanuse, theta) {
    var dx, dy, t;
    t = new Vertex;
    dx = hypotanuse * Math.sin((theta * Math.PI) / 180);
    dy = hypotanuse * Math.cos((theta * Math.PI) / 180);
    t.x = start.x - dx;
    t.y = start.y - dy;
    return t;
  };

  ClockMaths.prototype.drawLine = function(start, end, width) {
    if (width == null) {
      width = 1;
    }
    can.context.lineWidth = width;
    can.context.beginPath();
    can.context.moveTo(start.x, start.y);
    can.context.lineTo(end.x, end.y);
    return can.context.stroke();
  };

  return ClockMaths;

})();

Seconds = (function(_super) {
  __extends(Seconds, _super);

  Seconds.prototype.value = 0;

  Seconds.prototype.origin = null;

  Seconds.prototype.radius = null;

  Seconds.prototype.angle = 0;

  Seconds.prototype.width = 1;

  function Seconds(origin, radius, value) {
    this.origin = origin;
    this.radius = radius;
    this.value = value != null ? value : 0;
    this.update = __bind(this.update, this);
    this.angle -= this.value * 6;
  }

  Seconds.prototype.update = function() {
    var b;
    if (this.angle === -360) {
      this.angle = 0;
      can.trigger(can.events.m);
    }
    this.angle -= 6;
    b = this.CalculateSecondVertex(this.origin, this.radius, this.angle);
    return this.drawLine(a, b, this.width);
  };

  return Seconds;

})(ClockMaths);

Minutes = (function(_super) {
  __extends(Minutes, _super);

  Minutes.prototype.width = 3;

  function Minutes(origin, radius, value) {
    this.origin = origin;
    this.radius = radius;
    this.value = value != null ? value : 0;
    this.update = __bind(this.update, this);
    this.angleUpdate = __bind(this.angleUpdate, this);
    this.angle -= this.value * 6;
    can.on(can.events.m, this.angleUpdate);
  }

  Minutes.prototype.angleUpdate = function() {
    return this.angle -= 6;
  };

  Minutes.prototype.update = function() {
    var b;
    if (this.angle === -360) {
      this.angle = 0;
    }
    b = this.CalculateSecondVertex(this.origin, this.radius, this.angle);
    return this.drawLine(a, b, this.width);
  };

  return Minutes;

})(Seconds);

initCanvas = function() {
  return window.can = new CanvasH;
};

update = function() {
  can.element.width = can.element.width;
  seconds.update();
  return minutes.update();
};

window.addEventListener('load', function() {
  var d;
  initCanvas();
  window.a = new Vertex(300, 300);
  d = new Date;
  window.seconds = new Seconds(a, 100, d.getSeconds());
  window.minutes = new Minutes(a, 100, d.getMinutes());
  seconds.update();
  minutes.update();
  return setInterval(update, 1000);
});
